@startuml diagramma
package "AudioConverter"{
    class Converter{
        - name: String
        - quality: double
        - format: String
        - destination: String
        + Converter()
        + convertFile()
        - getFile()
        - renameFile()
    }

    class Validator {
        + obj: Converter
        + TYPE_NAME
        + TYPE_FORMAT
        + TYPE_DESTINATION
        + TYPE_QUALITY
        + Validator()
        + isValid()
        - isNameValid()
        - isFormatValid()
        - isDestinationValid()
        - isQualityValid()
        
    }

    class Main {
        + main(String[] args)
    }
}


@enduml