@startuml name
package "Progetto Audio"{
    class Converter{
        - name: String
        - quality: Type
        - format: String
        - destination: String
        + Converter()
        + convertFile()
        
    }

    class Validator {
        + obj: Converter
        + TYPE_NAME
        + TYPE_FORMAT
        + TYPE_DESTINATION
        + TYPE_QUALITY
        + Validator()
        + isValid(value, valueType)
        - isNameValid(value)
        - isFormatValid(value)
        - isDestinationValid(value)
        - isQualityValid(value)
        
    }

    class Main {
        + main(String[] args)
    }
}


@enduml